[package]
name = "sampler"
edition = "2021"
version = "0.1.0"

[dependencies]
anyhow = "1.0.87"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
ahash = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.5", features = ["derive"] }
bytes = "1.5"
