[package]
name = "sampler"
edition = "2024"
version = "0.1.0"

[dependencies]
anyhow = "1.0.87"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
